/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    products: Product;
    sites: Site;
    'site-memberships': SiteMembership;
    'brand-configs': BrandConfig;
    pages: Page;
    media: Media;
    customers: Customer;
    'service-requests': ServiceRequest;
    orders: Order;
    payments: Payment;
    partners: Partner;
    'partner-locations': PartnerLocation;
    'inventory-levels': InventoryLevel;
    fulfillments: Fulfillment;
    'ledger-accounts': LedgerAccount;
    'ledger-entries': LedgerEntry;
    settlements: Settlement;
    'payout-batches': PayoutBatch;
    payouts: Payout;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'site-memberships': SiteMembershipsSelect<false> | SiteMembershipsSelect<true>;
    'brand-configs': BrandConfigsSelect<false> | BrandConfigsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'service-requests': ServiceRequestsSelect<false> | ServiceRequestsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'partner-locations': PartnerLocationsSelect<false> | PartnerLocationsSelect<true>;
    'inventory-levels': InventoryLevelsSelect<false> | InventoryLevelsSelect<true>;
    fulfillments: FulfillmentsSelect<false> | FulfillmentsSelect<true>;
    'ledger-accounts': LedgerAccountsSelect<false> | LedgerAccountsSelect<true>;
    'ledger-entries': LedgerEntriesSelect<false> | LedgerEntriesSelect<true>;
    settlements: SettlementsSelect<false> | SettlementsSelect<true>;
    'payout-batches': PayoutBatchesSelect<false> | PayoutBatchesSelect<true>;
    payouts: PayoutsSelect<false> | PayoutsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domain?: string | null;
  /**
   * Auth0 Organization ID mapped to this tenant
   */
  auth0OrgId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  price: number;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  domain?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-memberships".
 */
export interface SiteMembership {
  id: number;
  tenant?: (number | null) | Tenant;
  user: number | User;
  site: number | Site;
  role: 'owner' | 'manager' | 'worker';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-configs".
 */
export interface BrandConfig {
  id: number;
  tenant?: (number | null) | Tenant;
  site: number | Site;
  logo?: (number | null) | Media;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  typography?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  site?: (number | null) | Site;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  site: number | Site;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant?: (number | null) | Tenant;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests".
 */
export interface ServiceRequest {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description: string;
  site?: (number | null) | Site;
  status?: ('pending' | 'in-progress' | 'completed' | 'rejected') | null;
  priority?: ('low' | 'medium' | 'high') | null;
  requestedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant?: (number | null) | Tenant;
  orderNumber: string;
  customer: number | Customer;
  site: number | Site;
  items?:
    | {
        product: number | Product;
        quantity: number;
        unitPrice: number;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  subtotal: number;
  fees?: number | null;
  total: number;
  currency: string;
  status?:
    | ('pending' | 'confirmed' | 'routed' | 'fulfilling' | 'delivered' | 'completed' | 'cancelled' | 'refunded')
    | null;
  paymentStatus?: ('unpaid' | 'authorized' | 'paid' | 'refunded' | 'failed') | null;
  fulfillmentStatus?: ('unfulfilled' | 'assigned' | 'in_transit' | 'delivered' | 'failed') | null;
  shippingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  placedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  tenant?: (number | null) | Tenant;
  order: number | Order;
  provider: string;
  providerIntentRef?: string | null;
  method?: ('ach' | 'rtp' | 'card' | 'pay_by_bank') | null;
  amount: number;
  currency: string;
  status?: ('requires_action' | 'authorized' | 'captured' | 'failed' | 'refunded') | null;
  capturedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  type?: ('supplier' | 'fulfillment' | 'hybrid') | null;
  status?: ('pending' | 'active' | 'suspended') | null;
  contactEmail?: string | null;
  credentials?:
    | {
        type?: string | null;
        identifier?: string | null;
        status?: ('pending' | 'verified' | 'expired' | 'rejected') | null;
        expiresAt?: string | null;
        id?: string | null;
      }[]
    | null;
  payoutMethod?: {
    provider?: string | null;
    accountRef?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-locations".
 */
export interface PartnerLocation {
  id: number;
  tenant?: (number | null) | Tenant;
  partner: number | Partner;
  label: string;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  lat?: number | null;
  lng?: number | null;
  serviceRadiusKm?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-levels".
 */
export interface InventoryLevel {
  id: number;
  tenant?: (number | null) | Tenant;
  product: number | Product;
  partnerLocation: number | PartnerLocation;
  quantityAvailable?: number | null;
  quantityReserved?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfillments".
 */
export interface Fulfillment {
  id: number;
  tenant?: (number | null) | Tenant;
  order: number | Order;
  partner: number | Partner;
  partnerLocation?: (number | null) | PartnerLocation;
  status?: ('assigned' | 'accepted' | 'picked_up' | 'in_transit' | 'delivered' | 'failed') | null;
  assignedAt?: string | null;
  deliveredAt?: string | null;
  trackingRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ledger-accounts".
 */
export interface LedgerAccount {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  type: 'platform_fee' | 'customer_funds' | 'partner_payable' | 'supplier_payable' | 'refunds_payable';
  ownerType?: ('platform' | 'partner' | 'supplier' | 'customer') | null;
  ownerRef?: string | null;
  currency: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ledger-entries".
 */
export interface LedgerEntry {
  id: number;
  tenant?: (number | null) | Tenant;
  transactionId: string;
  account: number | LedgerAccount;
  direction: 'debit' | 'credit';
  amount: number;
  currency: string;
  refType?: ('order' | 'settlement' | 'payout' | 'refund' | 'adjustment') | null;
  refId?: string | null;
  postedAt?: string | null;
  memo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settlements".
 */
export interface Settlement {
  id: number;
  tenant?: (number | null) | Tenant;
  order: number | Order;
  status?: ('pending' | 'allocated' | 'posted' | 'reconciled') | null;
  allocations?:
    | {
        payeeType?: ('platform' | 'supplier' | 'partner') | null;
        payeeRef?: string | null;
        amount?: number | null;
        basis?: string | null;
        id?: string | null;
      }[]
    | null;
  computedAt?: string | null;
  postedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-batches".
 */
export interface PayoutBatch {
  id: number;
  tenant?: (number | null) | Tenant;
  scheduledFor?: string | null;
  status?: ('pending' | 'processing' | 'paid' | 'failed') | null;
  provider?: string | null;
  totalAmount?: number | null;
  currency: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts".
 */
export interface Payout {
  id: number;
  tenant?: (number | null) | Tenant;
  batch: number | PayoutBatch;
  payee: number | Partner;
  amount: number;
  currency: string;
  status?: ('pending' | 'processing' | 'paid' | 'failed' | 'reversed') | null;
  providerRef?: string | null;
  method?: ('ach' | 'rtp' | 'card' | 'pay_by_bank') | null;
  settledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site-memberships';
        value: number | SiteMembership;
      } | null)
    | ({
        relationTo: 'brand-configs';
        value: number | BrandConfig;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'service-requests';
        value: number | ServiceRequest;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'partner-locations';
        value: number | PartnerLocation;
      } | null)
    | ({
        relationTo: 'inventory-levels';
        value: number | InventoryLevel;
      } | null)
    | ({
        relationTo: 'fulfillments';
        value: number | Fulfillment;
      } | null)
    | ({
        relationTo: 'ledger-accounts';
        value: number | LedgerAccount;
      } | null)
    | ({
        relationTo: 'ledger-entries';
        value: number | LedgerEntry;
      } | null)
    | ({
        relationTo: 'settlements';
        value: number | Settlement;
      } | null)
    | ({
        relationTo: 'payout-batches';
        value: number | PayoutBatch;
      } | null)
    | ({
        relationTo: 'payouts';
        value: number | Payout;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  auth0OrgId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  price?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  domain?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-memberships_select".
 */
export interface SiteMembershipsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  site?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-configs_select".
 */
export interface BrandConfigsSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  logo?: T;
  primaryColor?: T;
  secondaryColor?: T;
  typography?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests_select".
 */
export interface ServiceRequestsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  site?: T;
  status?: T;
  priority?: T;
  requestedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  customer?: T;
  site?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  fees?: T;
  total?: T;
  currency?: T;
  status?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  placedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  provider?: T;
  providerIntentRef?: T;
  method?: T;
  amount?: T;
  currency?: T;
  status?: T;
  capturedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  status?: T;
  contactEmail?: T;
  credentials?:
    | T
    | {
        type?: T;
        identifier?: T;
        status?: T;
        expiresAt?: T;
        id?: T;
      };
  payoutMethod?:
    | T
    | {
        provider?: T;
        accountRef?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-locations_select".
 */
export interface PartnerLocationsSelect<T extends boolean = true> {
  tenant?: T;
  partner?: T;
  label?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  lat?: T;
  lng?: T;
  serviceRadiusKm?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-levels_select".
 */
export interface InventoryLevelsSelect<T extends boolean = true> {
  tenant?: T;
  product?: T;
  partnerLocation?: T;
  quantityAvailable?: T;
  quantityReserved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfillments_select".
 */
export interface FulfillmentsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  partner?: T;
  partnerLocation?: T;
  status?: T;
  assignedAt?: T;
  deliveredAt?: T;
  trackingRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ledger-accounts_select".
 */
export interface LedgerAccountsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  ownerType?: T;
  ownerRef?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ledger-entries_select".
 */
export interface LedgerEntriesSelect<T extends boolean = true> {
  tenant?: T;
  transactionId?: T;
  account?: T;
  direction?: T;
  amount?: T;
  currency?: T;
  refType?: T;
  refId?: T;
  postedAt?: T;
  memo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settlements_select".
 */
export interface SettlementsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  status?: T;
  allocations?:
    | T
    | {
        payeeType?: T;
        payeeRef?: T;
        amount?: T;
        basis?: T;
        id?: T;
      };
  computedAt?: T;
  postedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-batches_select".
 */
export interface PayoutBatchesSelect<T extends boolean = true> {
  tenant?: T;
  scheduledFor?: T;
  status?: T;
  provider?: T;
  totalAmount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts_select".
 */
export interface PayoutsSelect<T extends boolean = true> {
  tenant?: T;
  batch?: T;
  payee?: T;
  amount?: T;
  currency?: T;
  status?: T;
  providerRef?: T;
  method?: T;
  settledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}